### PR TITLE
Bug & JSHint formatting fixes

### PR DESCRIPTION
**Pull request by gisdev-km**
Swapped protocol-specific designations to protocol-relative-urls (http://www.paulirish.com/2010/the-protocol-relative-url/)

Migrated geojson to separate file for ease of coding debugging.

Added and addressed JSHint formatting and errors.

### CODE REVIEW

**Comment by tforward** [comment]
Thanks, I have a few questions.
As per the protocol-specific designations to protocol-relative-urls this makes sense for the none https:// ones but the url provided states: "Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset." Is this un-true or did you not see the update?

In the highlight feature script you added handling for ie and opera. I actually had this code in there before but it was causing problems on mobile devices. When a user clicked a feature it would remain highlighted even after other features would pressed. Re-thinking about could I add a statement like layer.moveToback() or something in the section where the styles are reset for clickHightlightFeature function?

**Comment by tforward** [comment]
I did some more digging and it looks like https:// is the way to go when possible. Guess we both learned something new,

https://developers.google.com/speed/libraries/?csw=1
https://github.com/konklone/cdns-to-https#conclusion-cdns-should-redirect-to-https

**Comment by gisdev-km** [comment]
I agree that HTTPS should always be used but I have run into issues hard coding it and found the // designation to address the issues without worrying about something being internal, external or local and my browser getting finicky with cross-domain or other issues.

**Comment by gisdev-km** [comment]
> In the highlight feature script you added handling for ie and opera. I actually had this code in there before but it was causing problems on mobile devices. When a user clicked a feature it would remain highlighted even after other features would pressed. Re-thinking about could I add a statement like layer.moveToback() or something in the section where the styles are reset for clickHightlightFeature function?

This looks to be in the gh-pages and master branch [source file](https://raw.githubusercontent.com/tforward/calgary_pop_2014/gh-pages/scripts/leaflet.js) at lines 367-369.  Not something I actually added.

**Pull request merged**
